import subprocess
import json


def create_pr():
    subprocess.run([
        "gh", "pr", "create",
        "--title", "Autonomous Fix",
        "--body", "Generated by autonomous agent",
        "--fill"
    ])

    result = subprocess.run(
        ["gh", "pr", "view", "--json", "number"],
        capture_output=True,
        text=True
    )

    pr_number = json.loads(result.stdout)["number"]
    print(f"Created PR #{pr_number}")
    return pr_number


def get_pr_status(pr_number):
    result = subprocess.run(
        ["gh", "pr", "view", str(pr_number),
         "--json", "statusCheckRollup"],
        capture_output=True,
        text=True
    )
    return result.stdout


def parse_ci_results(ci_status):
    ci_data = json.loads(ci_status)
    checks = ci_data.get("statusCheckRollup", [])
    all_passed = all(check.get("conclusion") == "SUCCESS" for check in checks if check.get("conclusion"))
    return all_passed, checks


def extract_ci_logs(checks):
    ci_logs = "CI Checks Failed:\n"
    for check in checks:
        if check.get("conclusion") not in ["SUCCESS", None]:
            ci_logs += f"\n{check.get('name')}: {check.get('conclusion')}\n"
            if check.get("detailsUrl"):
                ci_logs += f"Details: {check.get('detailsUrl')}\n"
    return ci_logs


def get_latest_run_logs():
    """Get logs from the most recent workflow run"""
    runs = subprocess.run(
        ["gh", "run", "list", "--limit", "1", "--json", "databaseId"],
        capture_output=True,
        text=True
    )
    run_id = json.loads(runs.stdout)[0]["databaseId"]

    logs = subprocess.run(
        ["gh", "run", "view", str(run_id), "--log"],
        capture_output=True,
        text=True
    )

    return logs.stdout


def get_run_logs_by_id(run_id):
    """Get logs from a specific workflow run ID"""
    logs = subprocess.run(
        ["gh", "run", "view", str(run_id), "--log"],
        capture_output=True,
        text=True
    )
    return logs.stdout


def get_failed_test_logs():
    """Get logs from the test workflow run that triggered this repair agent"""
    # In GitHub Actions, get the workflow run that triggered us
    import os

    if os.environ.get("GITHUB_ACTIONS") == "true":
        # Get the triggering workflow run from the event
        runs = subprocess.run(
            ["gh", "run", "list", "--workflow", "Python Tests", "--limit", "5",
             "--json", "databaseId,conclusion,status"],
            capture_output=True,
            text=True
        )

        runs_data = json.loads(runs.stdout)

        # Find the most recent failed run
        for run in runs_data:
            if run.get("conclusion") == "failure":
                run_id = run["databaseId"]
                print(f"Fetching logs from failed test run #{run_id}")
                return get_run_logs_by_id(run_id)

    return None
